
# 系统管理服务

server:
  port: 8086


spring:
  datasource:
    url: jdbc:mysql://172.17.30.255:3306/nanchang-lamp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/nanchang-lamp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    freemarker:
      # 设置模板后缀名
      suffix: .ftl
      # 设置文档类型
      content-type: text/html
      # 设置页面编码格式
      charset: UTF-8
      # 设置页面缓存
      cache: false
      # 设置ftl文件路径
      template-loader-path: classpath:/templates




    ## thymeleaf模板设置
    thymeleaf:
      # 配置模板路径，默认是templates，可以不用配置
      prefix: classpath:/templates/
      # 文件类型
      suffix: .html
      # 模板的模式，支持 HTML, XML TEXT JAVASCRIPT
      mode: HTML5
      # 编码 可不用配置
      encoding: utf-8
      # 内容类别,可不用配置
      servlet.content-type: text/html
      # 开发配置为false,避免修改模板还要重启服务器
      cache: false

    ## json时间格式设置
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

    ## ehcache缓存配置
    cache:
      cache-names: wxCache
      jcache:
        config: classpath:ehcache.xml


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.pojo  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

# pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# logging:
#config: classpath:log4j2.yml

